### ISSUE TITLE
Advanced request options

### ISSUE THREAD

**Issue by saratovsource** [felipecsl/wombat#20]
Sometimes I need to emulate the xhr requests to the sites and pages (such as AJAX) or add different Headers in the request. It would be great to have the ability to specify the type of request (get, post, put, etc.)

**Comment by saratovsource** [comment]
@andrew-carroll I'll implement it on this week.

**Comment by andrew-carroll** [comment]
@saratovsource Did you end up being able to implement this?

**Comment by saratovsource** [comment]
@andrew-carroll yep, make PR today.
