### ISSUE TITLE
Return entire webpage

### ISSUE THREAD

**Issue by lachlanjc** [felipecsl/wombat#44]
I've used Wombat before for projects like [Noodles](http://www.getnoodl.es/) that require a simple web scraper, but now I'm trying to pull back the *entirety* of the web page. I want everything — the head, the body, the contents — not just something specific. Is Wombat able to do this?

**Comment by felipecsl** [comment]
You should probably just use straight [Mechanize](https://github.com/sparklemotion/mechanize) or [Nokogiri](https://github.com/sparklemotion)
