### ISSUE TITLE
Unable to activate mechanize-2.7.3. Gem::LoadError

### ISSUE THREAD

**Issue by lokeshjain2008** [felipecsl/wombat#46]
Sorry i made a silly mistake. i just tried `wombat` in my `pry` session and unable to use this great gem.
I need to solve this ASAP to complete my task.

```ruby
require 'wombat'
Gem::LoadError: Unable to activate mechanize-2.7.3, because mime-types-1.25.1 conflicts with mime-types (~> 2.0)
```

**Comment by felipecsl** [comment]
you probably have a gem versions conflict on your local config. Use a Gemfile to fix your dependencies.
