### ISSUE TITLE
Cannot run the example code.

### ISSUE THREAD

**Issue by lyenliang** [felipecsl/wombat#55]
Hi, I got `wombat.rb:14:in block (3 levels) in <main>': undefined method gsub' for nil:NilClass (NoMethodError)` error when running the example code at the introduction page of wombat.

I guess the reason for this error is that github has changed its home page's code. This makes the variable `e` become nil.

Anyone knows how to fix this problem? I'm not familiar with xpath. I just started learning xpath.

**Comment by felipecsl** [comment]
yeah that's definitely it. I wrote that example a long time ago and the github page is no longer the same. I'll update the examples to reflect the current page.

**Comment by Brotakuu** [comment]
Could you update the example? It would be helpful. Thanks!

**Comment by felipecsl** [comment]
sorry i've been really out of time recently. please feel free to send a PR

**Comment by felipecsl** [comment]
Fixed by #59
