### ISSUE TITLE
Wombat is a scraper. I don't think it is a crawler.

### ISSUE THREAD

**Issue by ghost** [felipecsl/wombat#6]
From what I can tell, wombat isn't a crawler. Is this correct?

**Web scraping**, to use a minimal definition, is the process of processing a web document and extracting information out of it. You can do web scraping without doing web crawling. [Wikipedia on web scraping](http://en.wikipedia.org/wiki/Web_scraping)

**Web crawling**, to use a minimal definition, is the process of iteratively finding and fetching web links starting from a list of seed URL's. Strictly speaking, to do web crawling, you have to do some degree of web scraping (to extract the URL's.) [Wikipedia on web crawlers](http://en.wikipedia.org/wiki/Web_crawler)

**Comment by StephenOTT** [comment]
@felipecsl was depth control ever added?

**Comment by felipecsl** [comment]
@StephenOTT not yet. I sounds like it could use that feature though. I'll see if I can get it implemented for next version

**Comment by StephenOTT** [comment]
I am looking to recreate the recursive functionality that FMiner provides:
http://www.fminer.com

The Ability to CSS or Xpath some links on the page and continue to follow/iterate through each of the pages.  On each page the user should be able to capture information.  Common examples of pages with "Next" Buttons or Hierarchical based data structures that are spread over multiple pages.
