### ISSUE TITLE
`set_proxy` not working

### ISSUE THREAD

**Issue by bachand** [felipecsl/wombat#66]
I tried out a slightly modified version of the example provided:

```ruby
require 'wombat'

class HeadersScraper
  include Wombat::Crawler

  base_url "http://www.rubygems.org"
  path "/"

  set_proxy("localhost", 8888)
end
```

I get this error:
```shell
/Users/michael/.rvm/gems/ruby-2.3.1/gems/wombat-2.5.1/lib/wombat/property/locators/factory.rb:34:in `locator_for': Unknown property format 8888. (Wombat::Property::Locators::UnknownTypeException)
```

Here's my setup:
- Ruby 2.3.1
- Wombat 2.5.1
- Nokogiri 1.8.0
- Mechanize 2.7.5

Moving this to the `configure` block is a workaround:

```ruby
Wombat.configure do |config|
  config.set_proxy("localhost", 8888)
end
```

**Comment by felipecsl** [comment]
Hi there @bachand 😄 
I've updated the [wiki doc](https://github.com/felipecsl/wombat/wiki/Configuration) to reflect this. It was indeed wrong. Thanks!
